name: your_environment_name
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - flask
  - spotipy
  - python-dotenv
  - scikit-learn
  - sqlalchemy
  - sympy
  - xgboost
  - requests
  - mkl-service>=2.4.0
  - mkl-random>=1.2.4
  - pip
  - pip:
    - render